version: "3.2"

services:
  api:
    image: casperpunks-api 
    build:
      context: "../."
      dockerfile: api/Dockerfile.prod
    environment:
      - NODE_ENV=development
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_CLUSTER_URL=${MONGO_CLUSTER_URL}
      - CASPER_CHAIN_NAME=${CASPER_CHAIN_NAME}
      - CASPER_NODE_ADDRESS=${CASPER_NODE_ADDRESS}
      - CASPER_EVENT_STREAM_ADDRESS=${CASPER_EVENT_STREAM_ADDRESS}
      - CASPER_CONTRACT_HASH=${CASPER_CONTRACT_HASH}
      - CASPER_PRIVATE_KEY=${CASPER_PRIVATE_KEY}
      - CASPER_PRIVATE_KEY_VARIANT=${CASPER_PRIVATE_KEY_VARIANT}
      - CASPER_SECRET
      - SUBMISSION_EXP_DATE
    restart: on-failure
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ../.
      dockerfile: frontend/Dockerfile.prod
    image: casperpunks-frontend
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=${API_URL}
      - REACT_APP_NFT_PREFIX=${NFT_PREFIX}
      - REACT_APP_S3_URL=${S3_URL}
      - REACT_APP_IPFS_URL=${IPFS_URL}
      - REACT_APP_GTM_ID=${GTM_ID}
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - api

  server:
    build:
      context: "../."
      dockerfile: server/Dockerfile
    image: casperpunks-server
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - frontend
      - api
