version: "3.2"

services:
  server:
    image: nginx
    environment:
      - NGINX_NODE_RPC=${NODE_URL}
    volumes:
    - ./../server/templates:/etc/nginx/templates
    - ./../server/nginx.conf:/etc/nginx/nginx.conf
    - ./../server/includes:/etc/nginx/my-includes
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - frontend

  frontend:
    build:
      context: ../.
      dockerfile: frontend/Dockerfile.dev
    image: casperselfie-reedem
    environment:
      - NODE_ENV=development
    restart: on-failure
    volumes:
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
      - ./../frontend:/app
    ports:
      - "4000:4000"
    depends_on:
      - api
