version: "3.2"

services:
  frontend:
    build:
      target: base
    image: blockexplorer-frontend
    command: sh -c "npm install && npm run start"
    volumes:
      - /usr/src/app/node_modules

  middleware:
    image: blockexplorer-middleware
    build:
      target: base
    command: sh -c "npm install && npm run dev"
    volumes:
      - /usr/src/app/node_modules
