version: "3.2"

services:
  frontend:
    build:
      context: ../.
      dockerfile: casper-trench/Dockerfile.dev
    image: casperpunks-frontend
    environment:
      - NODE_ENV=development
    restart: on-failure
    volumes:
      - /app/node_modules # prefer container's node_modules instead of volume-mounted ones
      - ./../casper-trench:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
